language: java

addons:
  apt:
    sources:
      - sourceline: 'deb http://repos.azulsystems.com/ubuntu stable main'
        key_url: 'http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems'
    packages:
      - zulu-8

after_success:
  - mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:jacoco -DsourceEncoding=UTF-8